version: "3.7"

services:  
  Database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/prd-ph-shoppinglist-db-root-pwd
      MYSQL_DATABASE: prd-shoppinglist
    ports:
      - "15909:3306"
    networks: 
      - prd-ph-shoppinglist
    volumes:
      - prd-ph-shoppinglist-database:/var/lib/mysql
    secrets:
      - prd-ph-shoppinglist-db-root-pwd

  Api:
    image: velocir4ptor/ph-shoppinglist-api:0.11.0
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PH_SL_DB_USERNAME_FILE: /run/secrets/prd-ph-shoppinglist-db-username
      PH_SL_DB_PASSWORD_FILE: /run/secrets/prd-ph-shoppinglist-db-password
    ports:
      - "12489:80"
    depends_on:
      - Database
    volumes:
      # - prd-ph-shoppinglist-api-tls:/app/ssl:ro # uncomment this for https support, see readme
      - prd-ph-shoppinglist-api-logs:/app/logs
      - prd-ph-shoppinglist-api-config:/app/config:ro
    networks: 
      - prd-ph-shoppinglist
    secrets:
      - prd-ph-shoppinglist-db-username
      - prd-ph-shoppinglist-db-password

  # LogCollector: # uncomment this for frontend log support
  #   image: velocir4ptor/web-assembly-log-collector:1.0.0
  #   ports:
  #     - "13880:80"
  #   volumes:
  #     - prd-ph-shoppinglist-log-collector-config:/app/config:ro
  #     - prd-ph-shoppinglist-log-collector-logs:/app/logs
  #   networks:
  #     - prd-ph-shoppinglist

  Frontend:
    image: velocir4ptor/ph-shoppinglist-frontend:0.11.0
    ports: 
      - "14000:80"
    depends_on:
      - Api
    volumes:
      - prd-ph-shoppinglist-frontend-config:/etc/nginx/conf.d:ro
      - {CONFIG_FOLDER_PATH}/appsettings.Production.json:/usr/share/nginx/html/wwwroot/appsettings.Production.json:ro
      # - prd-ph-shoppinglist-frontend-tls:/etc/nginx/ssl:ro # uncomment this for https support, see readme
    networks: 
      - prd-ph-shoppinglist

volumes:
  # prd-ph-shoppinglist-frontend-tls: # uncomment this for https support, see readme
  #   external: true
  # prd-ph-shoppinglist-api-tls:
  #   external: true
  prd-ph-shoppinglist-frontend-config:
    external: true
  prd-ph-shoppinglist-api-logs:
    external: true
  prd-ph-shoppinglist-api-config:
    external: true
  prd-ph-shoppinglist-database:
    external: true
  # prd-ph-shoppinglist-log-collector-config: # uncomment this for frontend log support
  #   external: true
  # prd-ph-shoppinglist-log-collector-logs:
  #   external: true

networks:
  prd-ph-shoppinglist:
    name: prd-ph-shoppinglist

secrets:
  prd-ph-shoppinglist-db-username:
    external: true
  prd-ph-shoppinglist-db-password:
    external: true
  prd-ph-shoppinglist-db-root-pwd:
    external: true