version: "3.7"

services:  
  Database:
    image: jsurf/rpi-mariadb
    container_name: dev-ph-sl-db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: dev-shoppinglist
    ports:
      - "15906:3306"
    networks: 
      - dev-ph-shoppinglist
    volumes:
      - dev-ph-shoppinglist-database:/var/lib/mysql
    restart: unless-stopped

  Api:
    image:
    container_name: dev-ph-sl-api
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "12486:443"
    depends_on:
      - Database
    networks:
      - dev-ph-shoppinglist
    restart: unless-stopped

  Frontend:
    image: 
    container_name: dev-ph-sl-frontend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "13997:443"
    depends_on:
      - Api
    networks:
      - dev-ph-shoppinglist
    restart: unless-stopped


volumes:
  dev-ph-shoppinglist-database:
    external: true
networks:
  dev-ph-shoppinglist:
    name: dev-ph-shoppinglist