version: "3.7"

services:  
  Database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/dev-ph-shoppinglist-db-root-pwd
      MYSQL_DATABASE: dev-shoppinglist
    ports:
      - "15906:3306"
    networks: 
      - dev-ph-shoppinglist
    volumes:
      - dev-ph-shoppinglist-database:/var/lib/mysql
    secrets:
      - dev-ph-shoppinglist-db-root-pwd

  Api:
    image: velocir4ptor/ph-shoppinglist-api:0.10.2
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      PH_SL_DB_USERNAME_FILE: /run/secrets/dev-ph-shoppinglist-db-username
      PH_SL_DB_PASSWORD_FILE: /run/secrets/dev-ph-shoppinglist-db-password
    ports:
      - "12486:80"
    depends_on:
      - Database
    volumes:
    #  - dev-ph-shoppinglist-api-tls:/app/ssl:ro # uncomment this for https support, see readme
      - dev-ph-shoppinglist-api-logs:/app/logs
      - dev-ph-shoppinglist-api-config:/app/config:ro
    networks:
      - dev-ph-shoppinglist
    secrets:
      - dev-ph-shoppinglist-db-username
      - dev-ph-shoppinglist-db-password

  # LogCollector: # uncomment this for frontend log support
  #   image: velocir4ptor/web-assembly-log-collector:1.0.0
  #   ports:
  #     - "13879:80"
  #   volumes:
  #     - dev-ph-shoppinglist-log-collector-config:/app/config:ro
  #     - dev-ph-shoppinglist-log-collector-logs:/app/logs
  #   networks:
  #     - dev-ph-shoppinglist

  Frontend:
    image: velocir4ptor/ph-shoppinglist-frontend:0.10.2
    ports:
      - "13997:80"
    depends_on:
      - Api
    volumes:
      - dev-ph-shoppinglist-frontend-config:/etc/nginx/conf.d:ro
      - {CONFIG_FOLDER_PATH}/appsettings.Development.json:/usr/share/nginx/html/wwwroot/appsettings.Development.json:ro
      # - dev-ph-shoppinglist-frontend-tls:/etc/nginx/ssl:ro # uncomment this for https support, see readme
    networks:
      - dev-ph-shoppinglist

volumes:
  # dev-ph-shoppinglist-frontend-tls: # uncomment this for https support, see readme
  #   external: true
  # dev-ph-shoppinglist-api-tls:
  #   external: true
  dev-ph-shoppinglist-frontend-config:
    external: true
  dev-ph-shoppinglist-api-logs:
    external: true
  dev-ph-shoppinglist-api-config:
    external: true
  dev-ph-shoppinglist-database:
    external: true
  # dev-ph-shoppinglist-log-collector-config: # uncomment this for frontend log support
  #   external: true
  # dev-ph-shoppinglist-log-collector-logs:
  #   external: true

networks:
  dev-ph-shoppinglist:
    name: dev-ph-shoppinglist

secrets:
  dev-ph-shoppinglist-db-username:
    external: true
  dev-ph-shoppinglist-db-password:
    external: true
  dev-ph-shoppinglist-db-root-pwd:
    external: true