version: "3.7"

services:  
  Database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/prd-ph-shoppinglist-db-root-pwd
      MYSQL_DATABASE: prd-shoppinglist
    ports:
      - "15909:3306"
    networks: 
      - prd-ph-shoppinglist
    volumes:
      - prd-ph-shoppinglist-database:/var/lib/mysql
    secrets:
      - prd-ph-shoppinglist-db-root-pwd

  Api:
    image: velocir4ptor/ph-shoppinglist-api:0.10.0
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PH_SL_DB_CONNECTION_STRING_FILE: /run/secrets/prd-ph-shoppinglist-db-connection-string
    ports:
      - "12489:443"
    depends_on:
      - Database
    volumes:
      - prd-ph-shoppinglist-api-tls:/app/ssl
      - prd-ph-shoppinglist-api-logs:/app/logs
      - prd-ph-shoppinglist-api-config:/app/config
    networks: 
      - prd-ph-shoppinglist
    secrets:
      - prd-ph-shoppinglist-db-connection-string

  Frontend:
    image: velocir4ptor/ph-shoppinglist-frontend:0.10.0
    ports: 
      - "14000:443"
    depends_on:
      - Api
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - prd-ph-shoppinglist-frontend-config:/etc/nginx/conf.d
      - {CONFIG_FOLDER_PATH}/appsettings.Production.json:/usr/share/nginx/html/wwwroot/appsettings.Production.json
      - prd-ph-shoppinglist-frontend-tls:/etc/nginx/ssl
    networks: 
      - prd-ph-shoppinglist

volumes:
  prd-ph-shoppinglist-frontend-tls:
    external: true
  prd-ph-shoppinglist-frontend-config:
    external: true
  prd-ph-shoppinglist-api-tls:
    external: true
  prd-ph-shoppinglist-api-logs:
    external: true
  prd-ph-shoppinglist-api-config:
    external: true
  prd-ph-shoppinglist-database:
    external: true

networks:
  prd-ph-shoppinglist:
    name: prd-ph-shoppinglist

secrets:
  prd-ph-shoppinglist-db-connection-string:
    external: true
  prd-ph-shoppinglist-db-root-pwd:
    external: true