version: "3.7"

services:  
  Database:
    image: jsurf/rpi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: <insert-your-root-pwd-here>
      MYSQL_DATABASE: dev-shoppinglist
    ports:
      - "15906:3306"
    networks: 
      - dev-ph-shoppinglist
    volumes:
      - dev-ph-shoppinglist-database:/var/lib/mysql

  Vault:
    image: arm32v6/vault:latest
    environment:
      VAULT_LOCAL_CONFIG: '{"backend": {"file": {"path": "/vault/file"}}, "default_lease_ttl": "168h", "max_lease_ttl": "720h"}'
    ports:
      - "14776:8200"
    volumes:
      - dev-ph-shoppinglist-vault-file:/vault/file
      - dev-ph-shoppinglist-vault-config:/vault/config
      - dev-ph-shoppinglist-vault-tls:/opt/vault/tls
    networks:
      - dev-ph-shoppinglist
    cap_add:
      - IPC_LOCK
    command: server

  Api:
    image: <insert-your-image-here>
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      PH_SL_VAULT_USERNAME_FILE: /run/secrets/dev-ph-shoppinglist-vault-api-username
      PH_SL_VAULT_PASSWORD_FILE: /run/secrets/dev-ph-shoppinglist-vault-api-password
    ports:
      - "12486:443"
    depends_on:
      - Database
      - Vault
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - dev-ph-shoppinglist-api-tls:/app/ssl
      - dev-ph-shoppinglist-api-logs:/app/logs
    networks:
      - dev-ph-shoppinglist
    secrets:
      - dev-ph-shoppinglist-vault-api-password
      - dev-ph-shoppinglist-vault-api-username

  Frontend:
    image: <insert-your-image-here>
    ports:
      - "13997:443"
    depends_on:
      - Api
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - dev-ph-shoppinglist-frontend-config:/etc/nginx/conf.d/
      - dev-ph-shoppinglist-frontend-tls:/etc/nginx/ssl
    networks:
      - dev-ph-shoppinglist

volumes:
  dev-ph-shoppinglist-frontend-tls:
    external: true
  dev-ph-shoppinglist-frontend-config:
    external: true
  dev-ph-shoppinglist-api-tls:
    external: true
  dev-ph-shoppinglist-database:
    external: true
  dev-ph-shoppinglist-vault-file:
    external: true
  dev-ph-shoppinglist-vault-config:
    external: true
  dev-ph-shoppinglist-vault-tls:
    external: true

networks:
  dev-ph-shoppinglist:
    name: dev-ph-shoppinglist

secrets:
  dev-ph-shoppinglist-vault-api-password:
    external: true
  dev-ph-shoppinglist-vault-api-username:
    external: true