version: "3.7"

services:  
  Database:
    image: jsurf/rpi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: <insert-your-root-pwd-here>
      MYSQL_DATABASE: dev-shoppinglist
    ports:
      - "15906:3306"
    networks: 
      - dev-ph-shoppinglist
    volumes:
      - dev-ph-shoppinglist-database:/var/lib/mysql

  Api:
    image: <insert-your-image-here>
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      PH_SL_DB_CONNECTION_STRING_FILE: /run/secrets/dev-ph-shoppinglist-db-connection-string
    ports:
      - "12486:443"
    depends_on:
      - Database
    volumes:
      - dev-ph-shoppinglist-api-tls:/app/ssl
      - dev-ph-shoppinglist-api-logs:/app/logs
    networks:
      - dev-ph-shoppinglist
    secrets:
      - dev-ph-shoppinglist-db-connection-string

  Frontend:
    image: <insert-your-image-here>
    ports:
      - "13997:443"
    depends_on:
      - Api
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - dev-ph-shoppinglist-frontend-config:/etc/nginx/conf.d/
      - dev-ph-shoppinglist-frontend-tls:/etc/nginx/ssl
    networks:
      - dev-ph-shoppinglist

volumes:
  dev-ph-shoppinglist-frontend-tls:
    external: true
  dev-ph-shoppinglist-frontend-config:
    external: true
  dev-ph-shoppinglist-api-tls:
    external: true
  dev-ph-shoppinglist-database:
    external: true

networks:
  dev-ph-shoppinglist:
    name: dev-ph-shoppinglist

secrets:
 dev-ph-shoppinglist-db-connection-string:
   external: true