version: "3.7"

services:  
  Database:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/dev-ph-shoppinglist-db-root-pwd
      MYSQL_DATABASE: dev-shoppinglist
    ports:
      - "15906:3306"
    networks: 
      - dev-ph-shoppinglist
    volumes:
      - dev-ph-shoppinglist-database:/var/lib/mysql
    secrets:
      - dev-ph-shoppinglist-db-root-pwd

  Api:
    image: velocir4ptor/ph-shoppinglist-api:0.10.0
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      PH_SL_DB_CONNECTION_STRING_FILE: /run/secrets/dev-ph-shoppinglist-db-connection-string
    ports:
      - "12486:443"
    depends_on:
      - Database
    volumes:
      - dev-ph-shoppinglist-api-tls:/app/ssl
      - dev-ph-shoppinglist-api-logs:/app/logs
      - dev-ph-shoppinglist-api-config:/app/config
    networks:
      - dev-ph-shoppinglist
    secrets:
      - dev-ph-shoppinglist-db-connection-string

  Frontend:
    image: velocir4ptor/ph-shoppinglist-frontend:0.10.0
    ports:
      - "13997:443"
    depends_on:
      - Api
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - dev-ph-shoppinglist-frontend-config:/etc/nginx/conf.d
      - {CONFIG_FOLDER_PATH}/appsettings.Development.json:/usr/share/nginx/html/wwwroot/appsettings.Development.json
      - dev-ph-shoppinglist-frontend-tls:/etc/nginx/ssl
    networks:
      - dev-ph-shoppinglist

volumes:
  dev-ph-shoppinglist-frontend-tls:
    external: true
  dev-ph-shoppinglist-frontend-config:
    external: true
  dev-ph-shoppinglist-api-tls:
    external: true
  dev-ph-shoppinglist-api-logs:
    external: true
  dev-ph-shoppinglist-api-config:
    external: true
  dev-ph-shoppinglist-database:
    external: true

networks:
  dev-ph-shoppinglist:
    name: dev-ph-shoppinglist

secrets:
  dev-ph-shoppinglist-db-connection-string:
    external: true
  dev-ph-shoppinglist-db-root-pwd:
    external: true