version: "3.7"

services:  
  Database:
    image: jsurf/rpi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: <insert-your-root-pwd-here>
      MYSQL_DATABASE: prd-shoppinglist
    ports:
      - "15909:3306"
    networks: 
      - prd-ph-shoppinglist
    volumes:
      - prd-ph-shoppinglist-database:/var/lib/mysql

  Api:
    image: <insert-your-image-here>
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PH_SL_DB_CONNECTION_STRING_FILE: /run/secrets/dev-ph-shoppinglist-db-connection-string
    ports:
      - "12489:443"
    depends_on:
      - Database
    networks: 
      - prd-ph-shoppinglist
    secrets:
      - prd-ph-shoppinglist-db-connection-string

  Frontend:
    image: <insert-your-image-here>
    ports: 
      - "14000:443"
    depends_on:
      - Api
    networks: 
      - prd-ph-shoppinglist

volumes:
  prd-ph-shoppinglist-database:
    external: true

networks:
  prd-ph-shoppinglist:
    name: prd-ph-shoppinglist

secrets:
 prd-ph-shoppinglist-db-connection-string:
   external: true