version: "3.7"

services:  
  Database:
    image: jsurf/rpi-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: <insert-your-root-pwd-here>
      MYSQL_DATABASE: prd-shoppinglist
    ports:
      - "15909:3306"
    networks: 
      - prd-ph-shoppinglist
    volumes:
      - prd-ph-shoppinglist-database:/var/lib/mysql

  Api:
    image: <insert-your-image-here>
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      PH_SL_DB_CONNECTION_STRING_FILE: /run/secrets/prd-ph-shoppinglist-db-connection-string
    ports:
      - "12489:443"
    depends_on:
      - Database
    volumes:
      - prd-ph-shoppinglist-api-tls:/app/ssl
      - prd-ph-shoppinglist-api-logs:/app/logs
    networks: 
      - prd-ph-shoppinglist
    secrets:
      - prd-ph-shoppinglist-db-connection-string

  Frontend:
    image: <insert-your-image-here>
    ports: 
      - "14000:443"
    depends_on:
      - Api
    volumes:
      - /usr/local/share/ca-certificates:/usr/local/share/ca-certificates
      - prd-ph-shoppinglist-frontend-config:/etc/nginx/conf.d/
      - prd-ph-shoppinglist-frontend-tls:/etc/nginx/ssl
    networks: 
      - prd-ph-shoppinglist

volumes:
  prd-ph-shoppinglist-frontend-tls:
    external: true
  prd-ph-shoppinglist-frontend-config:
    external: true
  prd-ph-shoppinglist-api-tls:
    external: true
  prd-ph-shoppinglist-api-logs:
    external: true
  prd-ph-shoppinglist-database:
    external: true

networks:
  prd-ph-shoppinglist:
    name: prd-ph-shoppinglist

secrets:
 prd-ph-shoppinglist-db-connection-string:
   external: true