version: "3.7"

services:  
  Database:
    image: jsurf/rpi-mariadb
    container_name: prd-ph-sl-db
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: prd-shoppinglist
    ports:
      - "15909:3306"
    networks: 
      - prd-ph-shoppinglist
    volumes:
      - prd-ph-shoppinglist-database:/var/lib/mysql
    restart: unless-stopped

  Api:
    image:
    container_name: prd-sl-ph-api
    environment:
      ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "12489:443"
    depends_on:
      - Database
    networks: 
      - prd-ph-shoppinglist
    restart: unless-stopped

  Frontend:
    image: 
    container_name: prd-ph-sl-frontend
    environment: 
      ASPNETCORE_ENVIRONMENT: Production
    ports: 
      - "14000:443"
    depends_on:
      - Api
    networks: 
      - prd-ph-shoppinglist
    restart: unless-stopped


volumes:
  prd-ph-shoppinglist-database:
    external: true
networks:
  prd-ph-shoppinglist:
    name: prd-ph-shoppinglist